### PR TITLE
Add coffeelint gem for CoffeeLint hook

### PR DESCRIPTION
**Pull request by KarenVentura**
- Add new config for git hooks
- Remove RubyLint
- Add CoffeeLint gem for CoffeeLint hook

### CODE REVIEW

**Comment by mumoc** [comment]
Like the idea you added CoffeLint but why remove Ruby? as it duplicated? if so, this LGTM

**Comment by mumoc** [comment]
Just update the branch before merging ^^

**Comment by KarenVentura** [comment]
because RubyLint is only for ruby code and we have Rails syntax, this raises a lot of errors.

**Comment by mumoc** [comment]
Update your branch and merge ^^

**Pull request merged**
